# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/6e16aca3-b202-4937-b847-43a95e3d0854";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/05433556-a58d-4899-b9a9-405d4d56e458";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/B4C2-DEF9";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/13d2a2b0-1b7d-40a8-9137-a9df8ea4f55e"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
