name: Update Flake

on:
  schedule:
    # every day at 3am UTC
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  updates:
    name: "Update the flake.lock"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - name: "flake.lock: Update"
        run: |
          git config user.name 'github-actions'
          git config user.email 'action@github.com'
          nix flake update --commit-lock-file
          git push
